import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

const main_font = Nunito({
	subsets: ["latin", "cyrillic"],
	variable: "--font-main",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App123123",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ru" className={`${main_font.variable} font-main`}>
			<body>{children}</body>
		</html>
	);
}
